apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-environment
resources:
- ../../base
- pv-test.yaml
- namespace.yaml

secretGenerator:
- name: maria-db-secret
  namespace: test-environment
  literals:
  - password=admin
- name: database-access
  namespace: test-environment
  literals:
  - password=admin
generatorOptions:
  disableNameSuffixHash: true
