apiVersion: v1
kind: Secret
metadata:
    name: database-access
type: kubernetes.io/basic-auth
stringData:
    mariadb-password: ENC[AES256_GCM,data:DP0SplVku+Ip,iv:fEoC6uE/sT7TrjiUCdZSsK03Gj8rFP7gGr/pmJjjQTw=,tag:u0l78Nddc2maKBtcGd7rKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOb1lHaVArMDBwaVltY3NN
            OVIwcHlZY00yalEvbFNVNFl6WUJuOG4relE4CjhnYVI0Y3RNMzdNeGhEOTFSWFRn
            V2NSQW5Mb0x3UURBVmMrMk11eWdaQlkKLS0tIHZrdU1UVFNvOFZ2Z3ZGaXJhalFZ
            UHNjKzM1RmFlblFzcmQ5cWNqSnhlUG8KFoMoVe4T6q43AsrpCwIr7ro6FHUI2Kyc
            AzoqzmYPyD3bOUcLE8/LCGDN/uZMUAAtt4lzO6igIhMi5eAnFfgr4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kwd98tcgdnn067kv43xj2uwjnuylpmhw9k8jqd2gduswgk6u7fpsn7my9y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T09:31:44Z"
    mac: ENC[AES256_GCM,data:+CmrvxHxSX/qWRN4eNSmiSRbSYpnwft4IOyYknDlnjTzfflc6kvoQH5kqzyb6t8k4d34eN7+SM7U+a3LoMW2e9C4ZvNcbgvPOeTq86LrmLkSzyytpuX4z2mrnPqsDd2K778coDHhevJe2SelqYppQEdswNxgB2lHKdp3iUOPO78=,iv:kmXdrzPcq3WKMPJBVpCuzgRmu0SwwoNg5kcsuhgzogY=,tag:TEDgg2FvIwkri+7tdRhFnw==,type:str]
    version: 3.13.1
