apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production-ready
resources:
- maria-db-secret.yaml
- pv-prod.yaml
- namespace.yaml
- database-access.yaml
- yourls-secret.yaml
