apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production-ready
resources:
- maria-db-secret.yaml
- pv-prod-1.yaml
- namespace.yaml
- database-access.yaml
- yourls-secret.yaml
- pv-prod-2.yaml
- pv-prod-3.yaml

#patches:
#  - path: maria-db-crs-patch.yaml
