apiVersion: v1
kind: Secret
metadata:
    name: maria-db-secret
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:Kw1dzh4dSsX+,iv:2DiZXpj7iw47A0rGVPTfjPuMmisYF291qpq5IEF5YSg=,tag:MQ5WnlgRi8uvMpaj6pS/rg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK1BUejQrbldoOTJURzQv
            d0NYem9GMFlmK2JtZWxHbVNHM2t0b3J0UzBzCjA0OFE3dHIwcFM0QXZtMndUZGFv
            em9PVU1Id2Ivbkt6VEpVRlFuVHVpTFEKLS0tIGJtbjlUOTYrclhlck1qL2pUZ2c2
            VXV4MURoWmxnbkhvY0lyeGFrZmdXTWsKL7df8oQ65etd+s0JL6aWUX2wWJHz/h9d
            8CNXLZroNQevgWAqGpeLkTUDsNa6K8W7x5Oyz5A53xqsMLO1Hf/jfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kwd98tcgdnn067kv43xj2uwjnuylpmhw9k8jqd2gduswgk6u7fpsn7my9y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T19:39:04Z"
    mac: ENC[AES256_GCM,data:Zi5Uv6QdtZ3S9NvLFxTCPqSs93gWRVVJJlrNUH16owLfVrfujXGwJHTxthmkbUTOLWsxp6+YMzYq9d13HgItwmUI4NbDepNumdPk+mjI5iKlWLzU9VykQyd4+F7YFU23TBOfsEChWra3SiMZmKTkE5oI3VUA5i/3hBMUt0aRTd8=,iv:aimSI30WJEuJA5L1D+LbI/Tr5r4bZ4zLviMcNjzpdk4=,tag:ZTVzq5LJd1NmZXVHhYq77g==,type:str]
    version: 3.13.1
