apiVersion: v1
kind: Secret
metadata:
    name: yourls-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:eb1O,iv:w+m+rF7taFlKy5kJGiuBWxLumj+avRMoo1ghS1V6wpk=,tag:Lgd/RSzwNN8HFrZCEN8CzQ==,type:str]
    password: ENC[AES256_GCM,data:/qwmnB9Fae5h,iv:Eyy9eMw3dbLDdn9kO7lmDPOJDjl3aXHHoinbtNpbEOg=,tag:prUv1egWypB3sLuLtr0TRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUjhnSEsyT2V6bnlDSEtN
            cVBoYnZKNDVsdzl1L29PallqYjVCbFoxTFdNCm56U1ZFeDBSSE9tTkdQb1lOVWVN
            eXhZUTRCZDNaczJtWEhieGJTU2o1d3cKLS0tIGNDMkp2NlRzenRrWFpLSGRmaC9h
            cVRxRFBObVpuRHAzQkhQT3R3b093dncKLlicprfhSsc/8+txovGLT79iwc4ySdqe
            9t1d8Dz1YTWa4LataV/1IqvmQd5+hOJ011icB75FkTe4ltB61qTFSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kwd98tcgdnn067kv43xj2uwjnuylpmhw9k8jqd2gduswgk6u7fpsn7my9y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T20:01:47Z"
    mac: ENC[AES256_GCM,data:uvlhPmhz+HwmJt8Mw255QHnjr015bcvmQpFC7tkz8tb8RJhu+jn5rgHnDTtCKaABwyw949mIUZ/pgklNgFjzjdxth7hNHr7EaUKBPDHnI6QvjnIujMzrXbkaX8hlzq/RVoYt1cbe6p1xbRCu0XuMBdJ1bJHcygrjxF/t31NxqCM=,iv:Na6KnrJ08/Ekdo8ixmrfHvkNyMl3MMikRZcte1GNsPs=,tag:5UJPCz5smkKMiI43pB+M2w==,type:str]
    version: 3.13.1
