apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: yourls
spec:
  values:
    yourls:
      domain: yourls.local.prod:30000
      existingSecret: yourls-secret
    persistence:
      enabled: true
      storageClass: local-storage
      accessModes:
        - ReadWriteOnce
      size: 1Gi
    resources:
      requests:
        memory: 250Mi
        cpu: 300m
      limits:
        memory: 350Mi
        cpu: 400m
